export const REPORT_HARIAN = {
  PENERIMAAN: 1,
  PENGELUARAN: 2,
}
export const REPORT_KARTU_PERSEDIAAN = {
  KARTU_PERSEDIAAN: 1,
  HASIL_AKHIR: 2,
  PERSEDIAAN_PERMUTU_KEBUN: 3,
  PERSEDIAAN_PERKOMODITI_KEBUN: 4,
  REKAP_PERSEDIAAN_KEBUN: 5,
  REKAP_PERSEDIAAN_HASIL_AKHIR_KEBUN: 6,
}
export const REPORT_PENJUALAN = {
  LOKAL_PERKEBUN: 1,
  LOKAL_NO_URUT_DO: 2,
  EKSPOR_PERKEBUN: 3,
  EKSPOR_NO_URUT_SC: 4,
  EKSPOR_NO_URUT_SC_PERKEBUN: 5,
}
export const REPORT_NOTA_TIMBANG_MASUK= {
  NOTA_TIMBANG_MASUK: 1,
}


